<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE operaciones [
<!ELEMENT operaciones (operacion+)>
<!ELEMENT operacion (venta|compra)+>
<!ELEMENT venta (titulosvendidos*)>
<!ELEMENT titulosvendidos (titulo+,cantidadtotal,entregado?,importe+)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT cantidadtotal (#PCDATA)>
<!ELEMENT entregado (#PCDATA)>
<!ELEMENT importe (#PCDATA)>
<!ELEMENT compra (tituloscomprados*)>
<!ELEMENT tituloscomprados (titulo_compra+,proveedor,fechacompra)>
<!ELEMENT titulo_compra (#PCDATA)>
<!ELEMENT proveedor (#PCDATA)>
<!ELEMENT fechacompra (dia,mes,año)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ATTLIST importe moneda CDATA #REQUIRED>
]>
<operaciones>
<operacion>
<venta>
<titulosvendidos>
<titulo>Don Quijote</titulo>
<titulo>Rimas y leyendas</titulo>
<cantidadtotal>2000</cantidadtotal>
<importe moneda="euros">4400</importe>
</titulosvendidos>
</venta>
<venta>
<titulosvendidos>
<titulo>Rinconete y Cortadillo</titulo>
<titulo>Sainetes</titulo>
<cantidadtotal>1000</cantidadtotal>
<entregado/>
<importe moneda="libras">290</importe>
</titulosvendidos>
</venta>
</operacion>
<operacion>
<compra>
<tituloscomprados>
<titulo_compra>De la Tierra a la Luna</titulo_compra>
<titulo_compra>Barbarroja</titulo_compra>
<proveedor>Editorial EDSA</proveedor>
<fechacompra>
<dia>10</dia>
<mes>6</mes>
<año>2018</año>
</fechacompra>
</tituloscomprados>
</compra>
<venta>
<titulosvendidos>
<titulo>Cinco semanas en globo</titulo>
<titulo>Sainetes</titulo>
<cantidadtotal>700</cantidadtotal>
<entregado/>
<importe moneda="euros">1490</importe>
</titulosvendidos>
</venta>
<compra>
<tituloscomprados>
<titulo_compra>De la Tierra a la Luna</titulo_compra>
<titulo_compra>Barbarroja</titulo_compra>
<proveedor>Editorial Recopila</proveedor>
<fechacompra>
<dia>2</dia>
<mes>12</mes>
<año>2017</año>
</fechacompra>
</tituloscomprados>
</compra>
</operacion>
</operaciones>

