=== arnau2104/LMSGI/XML/ex2/2.3.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE fabricant_tractors [
<!ELEMENT fabricant_tractors(comanda+)>
<!ELEMENT comanda (tractor+)>
<!ELEMENT tractor (component+)>
<!ELEMENT component (nom_fabricant,data_entrega,fragil,pes_component,nombre_serie,km_maxims?) >
<!ELEMENT nom_fabricant (#PCDATA) >
<!ELEMENT data_entrega(dia?,mes,any)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT any (#PCDATA)>
<!ELEMENT fragil (si|no)>
<!ELEMENT pes_component (#PCDATA)>
<!ELEMENT nombre_serie (#PCDATA)>
<!ELEMENT km_maxims (#PCDATA)>
<!ATTLIST pes_component unitat_pes (quilos|grams) #REQUIRED>
]>

=== arnau2104/LMSGI/XML/ex2/2.3.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE fabricant_tractors SYSTEM "2.3.dtd">

<fabricant_tractors>
  <comanda>
    <tractor>
      <component>
        <nom_fabricant> Tractors Menorca </nom_fabricant>
        <data_entrega>
          <mes>02</mes>
          <any>2024</any>
        </data_entrega>
        <fragil>no</fragil>
        <pes_component unitat_pes="quilos">5 </pes_component>
        <nombre_serie> #1052024589 </nombre_serie>
      </component>
    </tractor>
  </comanda>
</fabricant_tractors>
