=== arnau2104/LMSGI/XML/ex6/empleats.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="empleats">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="empleat" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nom">
                <xs:complexType>
                   <xs:simpleContent>
                     <xs:extension base="xs:string">
                      <xs:attribute name="id" type="xs:ID"/>
                     </xs:extension>
                    </xs:simpleContent>
                 </xs:complexType>
                </xs:element>
              <xs:element name="data_inici_contracte">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="dia" type="xs:gDay"/>
                    <xs:element name="mes" type="xs:gMonth"/>
                    <xs:element name="any" type="xs:gYear"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="lloc_ocupat" type="xs:string"/>
              <xs:element name="llocs_ocupats_anteriorment" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
              <xs:element name="cap_directe" type="xs:IDREF"/>
              <xs:element name="sou" type="xs:decimal"/>
              <xs:element name="titols_academics" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
              <xs:element name="seu">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="Madrid"/>
                    <xs:enumeration value="Barcelona"/>
                    <xs:enumeration value="Valencia"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="observacions" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="merits" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="demerits" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
           
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== arnau2104/LMSGI/XML/ex6/6.4.xml
<?xml version="1.0" encoding="UTF-8"?>
<empleats
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="empleats.xsd">
  <empleat>
    <nom id="emp1">Arnau</nom>
    <data_inici_contracte>
      <dia>---06</dia>
      <mes>--02</mes>
      <any>2024</any>
    </data_inici_contracte>
    <lloc_ocupat> Administrador de xarxa</lloc_ocupat>
    <cap_directe>emp1</cap_directe>
    <sou>1500</sou>
    <titols_academics>Grau Mitja en administracio de xarxes</titols_academics>
    <seu>Barcelona</seu>
    <observacions>
      <merits>Aprenentage rapid</merits>
    </observacions>
  </empleat>
  <empleat>
    <nom id="emp2">Marc</nom>
    <data_inici_contracte>
      <dia>---01</dia>
      <mes>--07</mes>
      <any>2021</any>
    </data_inici_contracte>
    <lloc_ocupat> Desarrolador web</lloc_ocupat>
    <cap_directe>emp2</cap_directe>
    <sou>1800</sou>
    <titols_academics>Grau Mitja en administracio de xarxes</titols_academics>
   <titols_academics>Grau Supero en desarrol d'aplicacion  web</titols_academics>
    <seu>Madrid</seu>
  </empleat>
  <empleat>
    <nom id="emp3">Carlos</nom>
    <data_inici_contracte>
      <dia>---10</dia>
      <mes>--01</mes>
      <any>2015</any>
    </data_inici_contracte>
    <lloc_ocupat>Recepcio</lloc_ocupat>
    <cap_directe>emp3</cap_directe>
    <sou>1200</sou>
    <seu>Valencia</seu>
    <observacions>
      <merits>Aprenentage rapid</merits>
    </observacions>
  </empleat>
  <empleat>
    <nom id="emp4">Dani</nom>
    <data_inici_contracte>
      <dia>---15</dia>
      <mes>--10</mes>
      <any>2020</any>
    </data_inici_contracte>
    <lloc_ocupat> Desarrolador web</lloc_ocupat>
    <llocs_ocupats_anteriorment>Administrador de xarxa</llocs_ocupats_anteriorment>
    <cap_directe>emp2</cap_directe>
    <sou>1800</sou>
    <titols_academics>Grau Mitja en administracio de xarxes</titols_academics>
   <titols_academics>Grau Supero en desarrol d'aplicacion  web</titols_academics>
    <seu>Madrid</seu>
    <observacions>
      <merits>Gran creativitat</merits>
      <merits>Gran inteligencia</merits>
      <demerits>S'enfada rapid</demerits>
    </observacions>
  </empleat>
  <empleat>
    <nom id="emp5">Cristina</nom>
    <data_inici_contracte>
      <dia>---01</dia>
      <mes>--07</mes>
      <any>2005</any>
    </data_inici_contracte>
    <lloc_ocupat>Contable</lloc_ocupat>
    <cap_directe>emp5</cap_directe>
    <sou>1400</sou>
    <titols_academics>Administracio de empreses</titols_academics>
    <seu>Madrid</seu>
  </empleat>
</empleats>
